# Generated by Django 3.2 on 2021-04-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='tracks',
            new_name='track',
        ),
    ]
